# Use the Jenkins SSH Agent image as the base
FROM jenkins/ssh-agent:jdk17

# Install Docker CLI in the agent container
USER root
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common && \
    curl -fsSL https://get.docker.com | sh

# Install sudo and allow jenkins user to run commands as root
RUN apt-get install -y sudo && \
    echo "jenkins ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN mkdir -p /home/jenkins/workspace && chown -R jenkins:jenkins /home/jenkins && chmod 700 /home/jenkins

# Add jenkins user to the docker group
# RUN groupadd -f docker && usermod -aG docker jenkins
RUN usermod -aG docker jenkins
RUN newgrp docker
