apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-webapi
  namespace: development
  labels:
    app: webapi
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: paulinedav/devopswebapi:latest
        ports:
        - containerPort: 8081