apiVersion: v1
kind: Service
metadata:
  name: dev-webapi-service
  namespace: development
spec:
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
