apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-webapi
  namespace: production
  labels:
    app: webapi
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: paulinedav/devopswebapi:latest
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 20