apiVersion: v1
kind: Service
metadata:
  name: prod-webapi-service
  namespace: production
spec:
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
  type: ClusterIP