apiVersion: v1
kind: Service
metadata:
  name: dev-webapi-service
  namespace: development
spec:
  selector:
    app: webapi
  ports:
    - protocol: TCP
      port: 8080        # Port exposé dans le service
      targetPort: 8080  # Port du container
      nodePort: 8081    # Port exposé sur le nœud
  type: NodePort
